loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()
wait(0.1)
loadstring(game:HttpGet("https://pastebin.com/raw/RXVhT9hC", true))()

